# Generated by Django 4.1.6 on 2023-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('dob', models.DateField(verbose_name='DoB')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('course', models.CharField(max_length=50, verbose_name='Course')),
                ('shirt', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('11', '11'), ('12', '12'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=3, verbose_name='Shirt')),
                ('delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('obs', models.CharField(max_length=240, null=True, verbose_name='Obs')),
            ],
        ),
    ]
