# Generated by Django 4.1.6 on 2023-04-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
    ]
