# Generated by Django 4.1.6 on 2023-09-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_remove_participant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
