# Generated by Django 4.1.6 on 2024-01-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='obs',
            field=models.CharField(max_length=100, null=True, verbose_name='Obs'),
        ),
    ]
