# Generated by Django 4.1.6 on 2023-06-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participant_shirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='shirt',
            field=models.CharField(choices=[('', ''), (' ', ' '), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('11', '11'), ('12', '12'), ('BL P', 'BL P'), ('BL M', 'BL M'), ('BL G', 'BL G'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=5, null=True, verbose_name='Shirt'),
        ),
    ]
