# Generated by Django 4.1.6 on 2024-03-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_participant_type_alter_participant_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='chip',
            field=models.IntegerField(default=None, verbose_name='Chip'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.CharField(max_length=50, null=True, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bib',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Bib'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.CharField(max_length=10, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=75, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='obs',
            field=models.CharField(max_length=50, null=True, verbose_name='Obs'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='shirt',
            field=models.CharField(max_length=5, null=True, verbose_name='Shirt'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.CharField(max_length=20, null=True, verbose_name='Type'),
        ),
    ]
