# Generated by Django 4.1.6 on 2024-07-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_participant_chip_participant_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='bib',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='obs',
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='participant',
            name='extra_shirt',
            field=models.CharField(blank=True, choices=[('BL PP', 'BL PP'), ('BL P', 'BL P'), ('BL M', 'BL M'), ('BL G', 'BL G'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=5, null=True, verbose_name='Extra Shirt'),
        ),
        migrations.AddField(
            model_name='participant',
            name='finisher',
            field=models.CharField(blank=True, choices=[('BL PP', 'BL PP'), ('BL P', 'BL P'), ('BL M', 'BL M'), ('BL G', 'BL G'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=5, null=True, verbose_name='Finisher'),
        ),
        migrations.AddField(
            model_name='participant',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='medal_record',
            field=models.BooleanField(default=False, verbose_name='Medal Record'),
        ),
        migrations.AddField(
            model_name='participant',
            name='name_received',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name Received'),
        ),
        migrations.AddField(
            model_name='participant',
            name='nation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nation'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='chip',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chip'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='shirt',
            field=models.CharField(blank=True, choices=[('BL PP', 'BL PP'), ('BL P', 'BL P'), ('BL M', 'BL M'), ('BL G', 'BL G'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=5, null=True, verbose_name='Shirt'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated At'),
        ),
    ]
