# Generated by Django 4.1.6 on 2024-07-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_remove_participant_bib_remove_participant_obs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='fisio',
            field=models.BooleanField(default=False, verbose_name='Fisio'),
        ),
        migrations.AddField(
            model_name='participant',
            name='group',
            field=models.CharField(blank=True, choices=[('CADEIRANTE', 'CADEIRANTE'), ('VISUAL', 'VISUAL'), ('ELITE', 'ELITE'), ('PUBLICO GERAL', 'PUBLICO GERAL'), ('PCD', 'PCD')], max_length=13, null=True, verbose_name='Group'),
        ),
    ]
