# Generated by Django 4.1.6 on 2024-07-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_participant_fisio_participant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fisio',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Fisio'),
        ),
    ]
